In [2]:
import warnings

# Ignore all warnings
warnings.filterwarnings("ignore")

In [3]:
from google.colab import drive
drive.mount('/content/drive')
%cd '/content/drive/My Drive/Plots'

Mounted at /content/drive
/content/drive/My Drive/Plots


#Import basic libraries

In [7]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import matplotlib.colors as mcolors
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder


from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import MultiLabelBinarizer, LabelEncoder

from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC



#Read the datasets

In [5]:

# Specify the file path to your CSV file
obrien = '/content/drive/My Drive/Plots/Obrien2022.csv'
vidoni = '/content/drive/My Drive/Plots/Vidoni2021.csv'
liu = '/content/drive/My Drive/Plots/LiuOnly2020.csv'

# Read the CSV file into a DataFrame
obrien = pd.read_csv(obrien, low_memory=False)
vidoni = pd.read_csv(vidoni, low_memory=False)
liu = pd.read_csv(liu, low_memory=False)



#Binary classification using SVM

In [8]:
# Load the dataset
data = vidoni

# Create binary labels
data['BinaryLabel'] = (data['TDType'] == 'ALGORITHM').astype(int)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(data['Comments'], data['BinaryLabel'], test_size=0.2, random_state=42)

# Convert text data into numerical representations (TF-IDF)
vectorizer = TfidfVectorizer()
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

# Train the SVM classifier
svm_classifier = SVC(kernel='linear')
svm_classifier.fit(X_train_tfidf, y_train)

# Evaluate the classifier
y_pred = svm_classifier.predict(X_test_tfidf)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.95      1.00      0.98       946
           1       1.00      0.04      0.08        47

    accuracy                           0.95       993
   macro avg       0.98      0.52      0.53       993
weighted avg       0.96      0.95      0.93       993



#BINARY Classification Using RF

In [9]:
# Load dataset
data = liu

# Preprocessing
X = data['Comments']
y_multi = data['TDType']
y_binary = (data['TDType'] == 'ALGORITHM').astype(int)

# Split data
X_train, X_test, y_multi_train, y_multi_test = train_test_split(X, y_multi, test_size=0.2, random_state=42)
_, _, y_binary_train, y_binary_test = train_test_split(X, y_binary, test_size=0.2, random_state=42)

# Feature extraction
tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)



# Binary classification for ALGORITHM detection
le = LabelEncoder()
y_binary_train_encoded = le.fit_transform(y_binary_train)
y_binary_test_encoded = le.transform(y_binary_test)

binary_clf = RandomForestClassifier()
binary_clf.fit(X_train_tfidf, y_binary_train_encoded)
binary_pred = binary_clf.predict(X_test_tfidf)

# Evaluation
#print("Multi-label classification report:\n", classification_report(y_multi_test_encoded, multi_pred))
print("Binary classification report for ALGORITHM detection:\n", classification_report(y_binary_test_encoded, binary_pred))


Binary classification report for ALGORITHM detection:
               precision    recall  f1-score   support

           0       0.99      1.00      1.00     11607
           1       0.98      0.63      0.77       290

    accuracy                           0.99     11897
   macro avg       0.99      0.82      0.88     11897
weighted avg       0.99      0.99      0.99     11897



In [ ]:
# Load dataset
data = liu

# Preprocessing
X = data['Comments']
y_multi = data['TDType']
y_binary = (data['TDType'] == 'ALGORITHM').astype(int)

# Split data
X_train, X_test, y_multi_train, y_multi_test = train_test_split(X, y_multi, test_size=0.2, random_state=42)
_, _, y_binary_train, y_binary_test = train_test_split(X, y_binary, test_size=0.2, random_state=42)

# Feature extraction
tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

# Binary classification for ALGORITHM detection
le = LabelEncoder()
y_binary_train_encoded = le.fit_transform(y_binary_train)
y_binary_test_encoded = le.transform(y_binary_test)

binary_clf = RandomForestClassifier()
binary_clf.fit(X_train_tfidf, y_binary_train_encoded)
binary_pred = binary_clf.predict(X_test_tfidf)

# Evaluation
#print("Multi-label classification report:\n", classification_report(y_multi_test_encoded, multi_pred))
print("Binary classification report for ALGORITHM detection:\n", classification_report(y_binary_test_encoded, binary_pred))


Binary classification report for ALGORITHM detection:
               precision    recall  f1-score   support

           0       0.99      1.00      1.00     11607
           1       0.98      0.63      0.77       290

    accuracy                           0.99     11897
   macro avg       0.99      0.82      0.88     11897
weighted avg       0.99      0.99      0.99     11897



#SVM Multi class

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.multioutput import MultiOutputClassifier
from sklearn.svm import SVC
from sklearn.metrics import classification_report

# Load the dataset
data = liu

# Split the dataset into features and target
X = data['Comments']
y = pd.get_dummies(data['TDType'])

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Convert text data into numerical representations (TF-IDF)
vectorizer = TfidfVectorizer()
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

# Train the multilabel classifier (SVM)
svm_classifier = SVC(kernel='linear')
multilabel_classifier = MultiOutputClassifier(svm_classifier)
multilabel_classifier.fit(X_train_tfidf, y_train)

# Evaluate the classifier
y_pred = multilabel_classifier.predict(X_test_tfidf)
target_names = y.columns
print(classification_report(y_test, y_pred, target_names=target_names))


                        precision    recall  f1-score   support

             ALGORITHM       0.94      0.33      0.49       290
         COMPATIBILITY       0.96      0.49      0.65       142
                DEFECT       0.93      0.46      0.62       213
                DESIGN       0.88      0.88      0.88      3452
         DOCUMENTATION       0.97      0.60      0.74        52
        IMPLEMENTATION       0.87      0.66      0.75       604
           MULTITHREAD       1.00      1.00      1.00         2
                  TEST       0.83      0.68      0.75       184
WITHOUT_CLASSIFICATION       0.97      0.98      0.98      6955
            removeType       0.00      0.00      0.00         2

             micro avg       0.94      0.90      0.92     11896
             macro avg       0.84      0.61      0.69     11896
          weighted avg       0.94      0.90      0.91     11896
           samples avg       0.89      0.90      0.89     11896



## TF-IDF Implementation

In [12]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [13]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [14]:
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer

# Load the dataset
data = vidoni

# Define function for text preprocessing
def preprocess_text(text):
    # Convert text to lowercase
    text = text.lower()
    # Remove special characters, numbers, and punctuation
    text = re.sub(r'[^a-z\s]', '', text)
    # Tokenize the text
    tokens = word_tokenize(text)
    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    tokens = [word for word in tokens if word not in stop_words]
    # Perform stemming
    stemmer = PorterStemmer()
    tokens = [stemmer.stem(word) for word in tokens]
    # Join tokens back into a string
    preprocessed_text = ' '.join(tokens)
    return preprocessed_text

# Apply text preprocessing to the Comments column
data['Comments'] = data['Comments'].apply(preprocess_text)

# Create TF-IDF vectorizer
tfidf_vectorizer = TfidfVectorizer()

# Fit the vectorizer and transform the Comments column into TF-IDF vectors
tfidf_matrix = tfidf_vectorizer.fit_transform(data['Comments'])

# Get the feature names (words) from the TF-IDF vectorizer
feature_names = tfidf_vectorizer.get_feature_names_out()

# Create a DataFrame to store TF-IDF scores for each word
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=feature_names)

# Add the TDType column to the DataFrame
tfidf_df['TDType'] = data['TDType']

# Group by TDType and calculate the mean TF-IDF score for each word
tfidf_scores_by_class = tfidf_df.groupby('TDType').mean()

# Get the top words for each class based on their TF-IDF scores
top_words_by_class = {}
for td_type, scores in tfidf_scores_by_class.iterrows():
    top_words_by_class[td_type] = scores.nlargest(10).index.tolist()

# Print the top words for each class
for td_type, words in top_words_by_class.items():
    print(f"Top words for class '{td_type}': {words}")


Top words for class 'ALGORITHM': ['fixm', 'todo', 'need', 'decid', 'add', 'deal', 'model', 'use', 'assum', 'data']
Top words for class 'ARCHITECTURE': ['slow', 'fixm', 'todo', 'memori', 'faster', 'speed', 'code', 'use', 'effici', 'make']
Top words for class 'BUILD': ['cmd', 'check', 'cran', 'avoid', 'note', 'packag', 'trick', 'global', 'workaround', 'hack']
Top words for class 'CODE': ['todo', 'fixm', 'need', 'use', 'check', 'hack', 'anymor', 'case', 'remov', 'work']
Top words for class 'DEFECT': ['fixm', 'work', 'fix', 'bug', 'doesnt', 'error', 'todo', 'fail', 'use', 'need']
Top words for class 'DESIGN': ['export', 'todo', 'function', 'object', 'class', 'fixm', 'need', 'use', 'list', 'gener']
Top words for class 'DOCUMENTATION': ['document', 'fixm', 'todo', 'function', 'add', 'undocu', 'develop', 'packag', 'roxygen', 'namespac']
Top words for class 'PEOPLE': ['fixmekelley', 'tom', 'todo', 'michel', 'michael', 'maxlen', 'temp', 'zero', 'stupid', 'clark']
Top words for class 'REQUIREMEN

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score
import pandas as pd

# Load the dataset
data = liu

# Split the dataset into features (X) and the target variable (y)
X = data['Comments']
y = data['TDType']

# Initialize the TF-IDF vectorizer
vectorizer = TfidfVectorizer(max_features=1000)  # You can adjust max_features as needed

# Convert text data into numerical TF-IDF features
X_tfidf = vectorizer.fit_transform(X)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_tfidf, y, test_size=0.2, random_state=42)

# Initialize the SVM classifier
svm_classifier = SVC(kernel='linear')  # You can choose different kernels based on your data

# Train the classifier
svm_classifier.fit(X_train, y_train)

# Make predictions
y_pred = svm_classifier.predict(X_test)

# Evaluate the classifier
print(classification_report(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))


#FASTTEXT Implementation
##Partial implementation

In [ ]:
pip install fasttext

In [ ]:
import fasttext

# Skipgram model :
model = fasttext.train_unsupervised('train.txt', model='skipgram')

# or, cbow model :
model = fasttext.train_unsupervised('train.txt', model='cbow')


In [ ]:
print(model.words)

['</s>', 'todo', 'fixm', 'use', 'need', 'nocov', 'check', 'work', 'data', 'test', 'function', 'case', 'add', 'set', 'error', 'file', 'code', 'fail', 'call', 'start', 'hack', 'make', 'remov', 'end', 'valu', 'fix', 'model', 'get', 'name', 'object', 'method', 'variabl', 'r', 'want', 'note', 'one', 'way', 'x', 'doesnt', 'time', 'handl', 'return', 'paramet', 'may', 'well', 'argument', 'column', 'better', 'dont', 'base', 'chang', 'matrix', 'could', 'line', 'first', 'also', 'list', 'avoid', 'type', 'local', 'workaround', 'na', 'warn', 'see', 'number', 'vector', 'group', 'differ', 'creat', 'like', 'new', 'user', 'sure', 'bug', 'issu', 'support', 'run', 'seem', 'trick', 'null', 'would', 'order', 'class', 'eg', 'might', 'instead', 'hope', 'allow', 'gener', 'packag', 'factor', 'encod', 'default', 'everi', 'version', 'someon', 'option', 'possibl', 'sampl', 'result', 'problem', 'utf', 'pass', 'probabl', 'select', 'think', 'true', 'miss', 'element', 'current', 'implement', 'luck', 'tri', 'done', 'cm

In [ ]:
print(model['Algorithm'])

[-0.01923659 -0.03826291  0.07134804 -0.2440327   0.15888806  0.01985367
  0.03319588  0.10935396 -0.10906585  0.02386821 -0.09607365  0.07034907
 -0.0118741   0.03864837 -0.02850566  0.10157031 -0.01747714  0.08010167
  0.07347971 -0.05447319 -0.09997132  0.02567375 -0.11691757  0.1907487
  0.03195964 -0.01426449  0.1694358   0.11902526 -0.08254462  0.19932416
 -0.25532827  0.06703003 -0.0416765  -0.07396021 -0.09468097 -0.02955039
 -0.20449331 -0.1950141  -0.13525121  0.07257954 -0.01515579 -0.01683534
  0.14189318 -0.00722726 -0.09954365 -0.0170407  -0.04882339 -0.03033301
  0.09874701  0.05149665 -0.06765055 -0.10636277 -0.12639472  0.05281369
 -0.0588594  -0.1857572   0.01220525  0.20289919 -0.16275075  0.11156417
 -0.0794157   0.14789799  0.17793624 -0.01543019 -0.08167998 -0.00454213
  0.08183704  0.0386159   0.12210261 -0.19682345 -0.24768063 -0.1901629
 -0.02237261 -0.08677626  0.11934367  0.00183974 -0.19299315  0.25221816
  0.08926781  0.12072149 -0.16266057 -0.13661209 -0.0

#Fasttext
###Partial

In [ ]:
import fasttext
from sklearn.model_selection import train_test_split

# Load dataset
data = vidoni

# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(data['Comments'], data['TDType'], test_size=0.2, random_state=42)

# Convert your data to fastText format and save to files
train_file = 'train.txt'
test_file = 'test.txt'

with open(train_file, 'w') as f:
    for text, label in zip(X_train, y_train):
        f.write(f'__label__{label} {text}\n')

with open(test_file, 'w') as f:
    for text, label in zip(X_test, y_test):
        f.write(f'__label__{label} {text}\n')

# Train fastText model
model = fasttext.train_supervised(input=train_file, epoch=25, lr=0.1, wordNgrams=2, dim=100, loss='softmax')

# Evaluate model
result = model.test(test_file)
print(f"Precision: {result[1]:.2f}")
print(f"Recall: {result[2]:.2f}")
print(f"F1 Score: {result[1] * result[2] * 2 / (result[1] + result[2]):.2f}")


Precision: 0.63
Recall: 0.63
F1 Score: 0.63


## NTLK


In [ ]:
from sklearn.naive_bayes import MultinomialNB
import nltk
from nltk.tokenize import word_tokenize
import spacy

# Download NLTK resources
nltk.download('punkt')

# Load English language model for spaCy
nlp = spacy.load("en_core_web_sm")

# Step 1: Load the dataset
data = liu



# Step 3: Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(data['Comments'], data['TDType'], test_size=0.2, random_state=42)

# Step 4: Feature Extraction (TF-IDF Vectorization)
vectorizer = TfidfVectorizer(max_features=5000, stop_words='english')  # You can adjust max_features as needed
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

# Step 5: Model Selection and Training
model = MultinomialNB()  # You can choose a different classifier based on your requirements
model.fit(X_train_tfidf, y_train)

# Step 6: Model Evaluation
y_pred = model.predict(X_test_tfidf)
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Named Entity Recognition with spaCy
def extract_entities(text):
    doc = nlp(text)
    entities = [(ent.text, ent.label_) for ent in doc.ents]
    return entities

# Example usage
text = "The company Apple Inc. is based in California."
print("Named Entities:")
print(extract_entities(text))

# Markov model with NLTK
class MarkovModel:
    def __init__(self):
        self.model = None

    def train(self, text):
        tokens = word_tokenize(text)
        bigrams = list(nltk.bigrams(tokens))
        self.model = nltk.ConditionalFreqDist(bigrams)

    def generate_text(self, seed, num_words=10):
        if self.model is None:
            raise ValueError("Model not trained")
        word = seed
        text = [word]
        for _ in range(num_words):
            if word not in self.model:
                break
            word = self.model[word].max()
            text.append(word)
        return ' '.join(text)

# Example usage
text = "This is a sample text for training the Markov model."
markov_model = MarkovModel()
markov_model.train(text)
generated_text = markov_model.generate_text("This")
print("Generated Text:")
print(generated_text)


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


Classification Report:
               precision    recall  f1-score   support

    ALGORITHM       0.00      0.00      0.00        47
 ARCHITECTURE       1.00      0.05      0.10        57
        BUILD       0.00      0.00      0.00        29
         CODE       0.49      1.00      0.65       428
       DEFECT       0.82      0.07      0.12       138
       DESIGN       1.00      0.02      0.05        43
DOCUMENTATION       0.00      0.00      0.00         7
       PEOPLE       0.00      0.00      0.00         8
 REQUIREMENTS       1.00      0.05      0.09        62
         TEST       0.97      0.64      0.77       151
    USABILITY       0.00      0.00      0.00        19
   VERSIONING       0.00      0.00      0.00         4

     accuracy                           0.54       993
    macro avg       0.44      0.15      0.15       993
 weighted avg       0.63      0.54      0.43       993

Confusion Matrix:
[[  0   0   0  47   0   0   0   0   0   0   0   0]
 [  0   3   0  54   0   0

#Markov Model

In [ ]:
pip install markovify

#Named Entity RECOG

In [16]:
import nltk
nltk.download('maxent_ne_chunker')
nltk.download('words')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping chunkers/maxent_ne_chunker.zip.
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Unzipping corpora/words.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


True

In [17]:
import pandas as pd

# Specify the file path to your CSV file
obrien = '/content/drive/My Drive/Plots/Obrien2022.csv'
vidoni = '/content/drive/My Drive/Plots/Vidoni2021.csv'
liu = '/content/drive/My Drive/Plots/LiuOnly2020.csv'

# Read the CSV file into a DataFrame
obrien = pd.read_csv(obrien, low_memory=False)
vidoni = pd.read_csv(vidoni, low_memory=False)
liu = pd.read_csv(liu, low_memory=False)


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.svm import SVC
from nltk import ne_chunk, word_tokenize, pos_tag
from nltk.tree import Tree

# Load the dataset
data = liu

# Define a function to extract named entities using NLTK's NER
def extract_named_entities(text):
    entities = []
    for chunk in ne_chunk(pos_tag(word_tokenize(text))):
        if isinstance(chunk, Tree):
            entities.append(" ".join([token for token, pos in chunk.leaves()]))
    return " ".join(entities)

# Apply the function to extract named entities from the Comments column
data['NamedEntities'] = data['Comments'].apply(extract_named_entities)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(data['NamedEntities'], data['TDType'], test_size=0.2, random_state=42)

# Convert named entities into features using CountVectorizer
vectorizer = CountVectorizer()
X_train_counts = vectorizer.fit_transform(X_train)
X_test_counts = vectorizer.transform(X_test)

# Train a Support Vector Classifier (SVC) model
model = SVC()
model.fit(X_train_counts, y_train)

# Evaluate the model
y_pred = model.predict(X_test_counts)
print("Classification Report:")
print(classification_report(y_test, y_pred))


In [ ]:

from sklearn.svm import SVC
import spacy

# Load the dataset
data = vidoni

# Preprocess the text data
data['Comments'] = data['Comments'].str.lower()

# Load the English language model for NER using spaCy
nlp = spacy.load('en_core_web_sm')

# Function to extract named entities from text using spaCy
def extract_named_entities(text):
    doc = nlp(text)
    named_entities = [ent.text for ent in doc.ents]
    return ' '.join(named_entities)

# Apply NER to extract named entities from the comments
data['NamedEntities'] = data['Comments'].apply(extract_named_entities)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(data['NamedEntities'], data['TDType'], test_size=0.2, random_state=42)

# Initialize a TF-IDF vectorizer
tfidf_vectorizer = TfidfVectorizer()

# Fit and transform the training data to TF-IDF vectors
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)

# Transform the testing data to TF-IDF vectors
X_test_tfidf = tfidf_vectorizer.transform(X_test)

# Initialize an SVM classifier
svm_classifier = SVC(kernel='linear')

# Train the SVM classifier on the TF-IDF vectors
svm_classifier.fit(X_train_tfidf, y_train)

# Make predictions on the testing data
predictions = svm_classifier.predict(X_test_tfidf)

# Print the classification report
print(classification_report(y_test, predictions))


               precision    recall  f1-score   support

    ALGORITHM       1.00      0.02      0.04        47
 ARCHITECTURE       0.00      0.00      0.00        57
        BUILD       0.00      0.00      0.00        29
         CODE       0.44      1.00      0.61       428
       DEFECT       0.64      0.05      0.09       138
       DESIGN       0.00      0.00      0.00        43
DOCUMENTATION       0.00      0.00      0.00         7
       PEOPLE       0.00      0.00      0.00         8
 REQUIREMENTS       0.00      0.00      0.00        62
         TEST       0.29      0.01      0.03       151
    USABILITY       0.00      0.00      0.00        19
   VERSIONING       1.00      0.25      0.40         4

     accuracy                           0.44       993
    macro avg       0.28      0.11      0.10       993
 weighted avg       0.37      0.44      0.28       993



In [ ]:
data

Comments  TDType  \
0                             # assume curl will handle    CODE   
1                                  # is this cacheable?    CODE   
2     # what impact should any(c("public", "private"...    CODE   
3                                 # requires validation    CODE   
4     # todo might need to put some params before an...    CODE   
...                                                 ...     ...   
4956              ## todo: remove this function (mvdl):    CODE   
4957          # todo: remove the function below. (mvdl)    CODE   
4958                            # obvious contradiction    TEST   
4959  # mip is sensitive to (very) large differences...    TEST   
4960  # this used to cause a crash after upgrading t...  DEFECT   

       NamedEntities  
0                  #  
1                     
2                     
3                     
4                     
...              ...  
4956               #  
4957               #  
4958               #  
4959  mip 11.08.2012  
4960               #  

[4961 rows x 3 columns]

#Word2VEc embeddings

In [ ]:
# Load the dataset
df = vidoni

# Feature Representation
# Treat each comment as a document and create a feature representation
comments = df['Comments']
td_types = df['TDType']

# Generate an alphabetical list of unigrams and count occurrence of each token
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(comments)

# Split the dataset into training, validation, and test sets
X_train, X_temp, y_train, y_temp = train_test_split(X, td_types, test_size=0.3, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

# Train the classifier
classifier = MultinomialNB()
classifier.fit(X_train, y_train)

# Evaluate Model Performance
# Calculate confusion matrix for resubstitution error
y_pred_train = classifier.predict(X_train)
conf_matrix_train = confusion_matrix(y_train, y_pred_train)
print("Confusion Matrix (Training):\n", conf_matrix_train)

# Evaluate the model on validation set
y_pred_val = classifier.predict(X_val)
print("Classification Report (Validation):\n", classification_report(y_val, y_pred_val))

# Evaluate the model on test set
y_pred_test = classifier.predict(X_test)
print("Classification Report (Test):\n", classification_report(y_test, y_pred_test))


Confusion Matrix (Training):
 [[  67    1    0  135    3    0    0    0    2    1    0    0]
 [   0  107    0   90    5    0    0    0    0    1    0    0]
 [   0    0   29   70    5    0    0    0    1    4    0    0]
 [   0    1    0 1372   11    0    0    0    2    2    0    0]
 [   0    0    0  128  351    0    0    0    1    3    0    0]
 [   0    0    0  111    6   34    0    0    2    1    0    0]
 [   0    0    0   29    7    0    5    0    0    1    0    0]
 [   0    0    0   10    2    0    0    0    0    0    0    0]
 [   0    0    0  133    6    0    0    0  116    1    0    0]
 [   0    1    0   85   12    0    0    0    0  453    0    0]
 [   1    0    0   41    1    0    0    0    0    2    4    0]
 [   0    0    0   14    1    0    0    0    0    0    0    1]]
Classification Report (Validation):
                precision    recall  f1-score   support

    ALGORITHM       0.40      0.06      0.10        36
 ARCHITECTURE       0.60      0.17      0.26        36
        BU

#WORD2VEC MODEL

In [ ]:
# Load dataset
df = vidoni

# Tokenize the comments
tokenized_comments = [word_tokenize(comment.lower()) for comment in df['Comments']]

# Train Word2Vec model
word2vec_model = Word2Vec(sentences=tokenized_comments, vector_size=100, window=5, min_count=1, workers=4)

# Save the trained model
word2vec_model.save('word2vec_model.bin')

In [ ]:
from nltk.tokenize import word_tokenize
from sklearn.linear_model import LogisticRegression


# Load your dataset with labeled data (Comments and TDType)
df = vidoni

# Tokenize the comments
tokenized_comments = [word_tokenize(comment.lower()) for comment in df['Comments']]

# Load the pre-trained Word2Vec model
word2vec_model = Word2Vec.load('word2vec_model.bin')

# Generate word embeddings for each comment
comment_embeddings = []
for tokens in tokenized_comments:
    embeddings = [word2vec_model.wv[token] for token in tokens if token in word2vec_model.wv]
    if embeddings:
        comment_embeddings.append(sum(embeddings) / len(embeddings))
    else:
        # If no word in the comment is present in the Word2Vec vocabulary, use a zero vector
        comment_embeddings.append([0] * word2vec_model.vector_size)

X_train, X_test, y_train, y_test = train_test_split(comment_embeddings, df['TDType'], test_size=0.2, random_state=42)

# Train a classifier (e.g., Logistic Regression)
classifier = LogisticRegression()
classifier.fit(X_train, y_train)

# Predict on the test set
y_pred = classifier.predict(X_test)

# Generate a classification report
report = classification_report(y_test, y_pred)
print(report)


               precision    recall  f1-score   support

    ALGORITHM       0.00      0.00      0.00        47
 ARCHITECTURE       0.00      0.00      0.00        57
        BUILD       0.00      0.00      0.00        29
         CODE       0.47      1.00      0.64       428
       DEFECT       1.00      0.01      0.01       138
       DESIGN       0.00      0.00      0.00        43
DOCUMENTATION       0.00      0.00      0.00         7
       PEOPLE       0.00      0.00      0.00         8
 REQUIREMENTS       0.00      0.00      0.00        62
         TEST       0.97      0.48      0.64       151
    USABILITY       0.00      0.00      0.00        19
   VERSIONING       0.00      0.00      0.00         4

     accuracy                           0.50       993
    macro avg       0.20      0.12      0.11       993
 weighted avg       0.49      0.50      0.37       993



#Binary Classification

In [ ]:
df = vidoni

# Preprocess the data
df['Comments'] = df['Comments'].apply(lambda x: x.lower())  # Convert to lowercase
df['Comments'] = df['Comments'].apply(lambda x: ' '.join(word_tokenize(x)))  # Tokenize

# Define the target variable
df['IsAlgorithm'] = (df['TDType'] == 'ALGORITHM').astype(int)

# Split the dataset into train and test sets
X_train, X_test, y_train, y_test = train_test_split(df['Comments'], df['IsAlgorithm'], test_size=0.2, random_state=42)

# Load the pre-trained Word2Vec model
word2vec_model = Word2Vec.load('word2vec_model.bin')

# Generate word embeddings for each comment
def generate_embeddings(comment):
    tokens = word_tokenize(comment)
    embeddings = [word2vec_model.wv[token] for token in tokens if token in word2vec_model.wv]
    if embeddings:
        return sum(embeddings) / len(embeddings)
    else:
        return [0] * word2vec_model.vector_size

X_train_embeddings = X_train.apply(generate_embeddings)
X_test_embeddings = X_test.apply(generate_embeddings)

# Train a logistic regression classifier
classifier = LogisticRegression()
classifier.fit(list(X_train_embeddings), y_train)

# Make predictions on the test set
y_pred = classifier.predict(list(X_test_embeddings))

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

classification_report = classification_report(y_test, y_pred)
print(classification_report)


Accuracy: 0.9526686807653575
              precision    recall  f1-score   support

           0       0.95      1.00      0.98       946
           1       0.00      0.00      0.00        47

    accuracy                           0.95       993
   macro avg       0.48      0.50      0.49       993
weighted avg       0.91      0.95      0.93       993



In [ ]:
print(df['IsAlgorithm'].unique())

[0 1]


#Experimenting with with  feature extraction techniques and vectorizers

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

# Load your dataset

df = vidoni

# Preprocess the data
df['Comments'] = df['Comments'].apply(lambda x: x.lower())  # Convert to lowercase
df['Comments'] = df['Comments'].apply(lambda x: ' '.join(word_tokenize(x)))  # Tokenize

# Split the dataset into train and test sets
X_train, X_test, y_train, y_test = train_test_split(df['Comments'], df['TDType'], test_size=0.2, random_state=42)

# Define different vectorizers
vectorizers = {
    'CountVectorizer': CountVectorizer(),
    'TfidfVectorizer': TfidfVectorizer(),
    'HashingVectorizer': HashingVectorizer()
}

# Experiment with different vectorizers and feature extraction techniques
for vectorizer_name, vectorizer in vectorizers.items():
    print(f"Experimenting with {vectorizer_name}...")

    # Transform the text data using the vectorizer
    X_train_vectorized = vectorizer.fit_transform(X_train)
    X_test_vectorized = vectorizer.transform(X_test)

    # Train a simple classifier (Logistic Regression) on the vectorized data
    clf = LogisticRegression(max_iter=1000)
    clf.fit(X_train_vectorized, y_train)

    # Evaluate the classifier on the test set
    y_pred = clf.predict(X_test_vectorized)

    # Print classification report
    print(f"Classification Report for {vectorizer_name}:")
    print(classification_report(y_test, y_pred))
    print("="*50)


Experimenting with CountVectorizer...
Classification Report for CountVectorizer:
               precision    recall  f1-score   support

    ALGORITHM       0.39      0.28      0.33        47
 ARCHITECTURE       0.69      0.39      0.49        57
        BUILD       0.73      0.38      0.50        29
         CODE       0.65      0.87      0.74       428
       DEFECT       0.51      0.46      0.49       138
       DESIGN       0.48      0.23      0.31        43
DOCUMENTATION       0.67      0.29      0.40         7
       PEOPLE       0.00      0.00      0.00         8
 REQUIREMENTS       0.50      0.34      0.40        62
         TEST       0.92      0.81      0.86       151
    USABILITY       0.62      0.26      0.37        19
   VERSIONING       0.50      0.50      0.50         4

     accuracy                           0.65       993
    macro avg       0.55      0.40      0.45       993
 weighted avg       0.64      0.65      0.63       993

Experimenting with TfidfVectorizer..

In [ ]:
pip install hmmlearn

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 161.1/161.1 kB 3.6 MB/s eta 0:00:00


####Donot run this cell : This code takes time to run and produces an error "Mix of label input types string and number" at the end.

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from hmmlearn import hmm
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

# Step 1: Load the dataset
data = vidoni

# Feature Extraction
vectorizer = TfidfVectorizer(max_features=1000)
X = vectorizer.fit_transform(data['Comments'])
y = data['TDType']

# Step: Model Training
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = hmm.GaussianHMM(n_components=10, covariance_type="full", n_iter=100)
model.fit(X_train.toarray())

# Step 5: Evaluation
y_pred = model.predict(X_test.toarray())
print(classification_report(y_test, y_pred))

ValueError: Mix of label input types (string and number)

#MARKOV MODEL

In [ ]:
from collections import defaultdict

# Load the dataset
data = vidoni

# Preprocess the data (tokenization)
comments = data['Comments'].str.split()

# Create the Markov model
markov_model = defaultdict(lambda: defaultdict(int))

# Train the model
for comment in comments:
    for i in range(len(comment) - 1):
        word, next_word = comment[i], comment[i + 1]
        markov_model[word][next_word] += 1

# Normalize the counts to get transition probabilities
for word in markov_model:
    total_transitions = sum(markov_model[word].values())
    for next_word in markov_model[word]:
        markov_model[word][next_word] /= total_transitions

# Example: Generate a sequence of words using the trained Markov model
current_word = 'start'
generated_sequence = [current_word]
for _ in range(10):  # Generate 10 words
    next_word = max(markov_model[current_word], key=markov_model[current_word].get)
    generated_sequence.append(next_word)
    current_word = next_word

# Print the generated sequence
print(' '.join(generated_sequence))


start # TODO: add the same as well; if someone wanted
